[package]
name = "kip-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kip-rs"
path = "mock_main.rs"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
rustyline = "14.0"
colored = "2.0"
atty = "0.2.14"
